### ISSUE TITLE
Cannot include via gradle

### ISSUE THREAD

**Issue by SumukhaK** [zion830/RangeTimePickerDialog#1]
Hi , 

when i add " implementation 'com.github.zion830:RangeTimePickerDialog:1.2' " in my android studio gradle it is showing the following error upon building project : 

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.zion830:RangeTimePickerDialog:1.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/zion830/RangeTimePickerDialog/1.2/RangeTimePickerDialog-1.2.pom
       - https://jcenter.bintray.com/com/github/zion830/RangeTimePickerDialog/1.2/RangeTimePickerDialog-1.2.pom
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by zion830** [comment]
@SumukhaK 
I'm sorry for the late reply. Thank you very much for your report!
I'll fix it soon.
